[technote]
id = "SITCOMTN-083"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-083.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-083"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Craig", family = "Lage"}
[[technote.authors]]
name = {given = "David", family = "Sanmartim"}